# Cloud Foundry Java Buildpack
# Copyright 2013-2016 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for the AppDynamics framework

#!/bin/bash -eu

#Adding controller-info configurations
APPD_CONF="-Dappdynamics.controller.hostName=${APPDYNAMICS_CONTROLLER_HOST_NAME} -Dappdynamics.controller.port=${APPDYNAMICS_CONTROLLER_PORT} -Dappdynamics.agent.applicationName=${APPDYNAMICS_AGENT_APPLICATION_NAME} -Dappdynamics.agent.tierName=${APPDYNAMICS_AGENT_TIER_NAME} -Dappdynamics.agent.nodeName=${OPENSHIFT_GEAR_UUID} -Dappdynamics.controller.ssl.enabled=${APPDYNAMICS_CONTROLLER_SSL_ENABLED}"

#test if variable  is defined and not empty
if [ -n "${APPDYNAMICS_AGENT_ACCOUNT_NAME+1}" ] && [ ! -z "${APPDYNAMICS_AGENT_ACCOUNT_NAME}" ] && [ -n "${APPDYNAMICS_AGENT_ACCOUNT_NAME+1}" ] && [ ! -z "${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}" ]; then
	APPD_CONF="${APPD_CONF} -Dappdynamics.agent.accountName=${APPDYNAMICS_AGENT_ACCOUNT_NAME} -Dappdynamics.agent.accountAccessKey=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}"
fi

export APPD_CONF_OPTS="${APPD_CONF}"